-- AlterEnum
ALTER TYPE "VerificationStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_VERIFIED';
ALTER TYPE "VerificationStatus" ADD VALUE IF NOT EXISTS 'STALE';
ALTER TYPE "VerificationStatus" ADD VALUE IF NOT EXISTS 'UNSUPPORTED';

-- AlterTable
ALTER TABLE "programs" ADD COLUMN IF NOT EXISTS "degreeLevel" TEXT NOT NULL DEFAULT 'Master',
ADD COLUMN IF NOT EXISTS "degreeType" TEXT NOT NULL DEFAULT 'MSc',
ADD COLUMN IF NOT EXISTS "studyField" TEXT NOT NULL DEFAULT 'Computer Science & IT',
ADD COLUMN IF NOT EXISTS "specialization" TEXT,
ADD COLUMN IF NOT EXISTS "campus" TEXT,
ADD COLUMN IF NOT EXISTS "studyMode" TEXT NOT NULL DEFAULT 'Full-time',
ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'English',
ADD COLUMN IF NOT EXISTS "duration" TEXT NOT NULL DEFAULT '2 Years',
ADD COLUMN IF NOT EXISTS "applicationMethod" TEXT NOT NULL DEFAULT 'Direct Portal',
ADD COLUMN IF NOT EXISTS "eligibilitySummary" TEXT,
ADD COLUMN IF NOT EXISTS "minimumGpa" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "englishRequirements" TEXT,
ADD COLUMN IF NOT EXISTS "sourceTitle" TEXT,
ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
